### ISSUE TITLE
你好，我是一个初学者，照着书做到第五章了，有些看不懂，问些问题，求解答。

### ISSUE THREAD

**Issue by qnxsgwy** [phodal/designiot-books#2]
目前照着书上例子已经可以获取到传感器数值，现在卡在数据上传进数据库保存的环节，前面讲的一直是如何对数据库中的某一个量的状态进行不断更新，但是只能记录下这个量的最后一个值。但是现在我想记录的是同一个变量（比如温度）在不同时间的不同值，查询的时候也可以查询一个个不同时间点上温度这个量的具体数值，这点在书上没有详细的讲解，不是很明白，我试了好几天也一直做不出来想要的效果。能否麻烦您详细讲解一下。
另外，书上说的Mongodb图形化界面怎么样才能实现呢？
完全初学者，对我这种什么都不会的纯小白，您书上写的还是太简略了，做着做着就觉得无从下手了，请稍微详细一些解答一下吧，拜托了。

**Comment by phodal** [comment]
问题一. 是不是判断语句没写好，没有代码，我这里也不好判断，你贴下代码吧。
问题二. MongoDB的图形化界面可以用： Robomongo

**Comment by qnxsgwy** [comment]
@phodal 写不出来自己的代码，目前是按照  https://github.com/phodal/designiot-code/blob/master/chapter5/rest/db.js  这个代码再做，感觉还是因为我不理解Mongodb的用法/(ㄒoㄒ)/~~

**Comment by phodal** [comment]
@qnxsgwy 代码本身应该是没有问题的，你再试试哈~~。可以借一本 MongoDB的书看看，或者买上看看教程
